version: '3'
services:
  mysql:
    image: mysql:8.0-debian
    container_name: mysql
    ports:
      - '6000:3306'
    restart: always
    env_file:
      - ./.env
    volumes:
      - ~/db/mysql-db:/var/lib/mysql/