"""create users table

Revision ID: 7eab40ad590e
Revises: 4f230d7f88b7
Create Date: 2023-03-30 16:47:42.256267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eab40ad590e'
down_revision = '4f230d7f88b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
